/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analyses/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness_api_v1_analyses_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{analysis_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Analysis Events */
        get: operations["stream_analysis_events_api_v1_analyses__analysis_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/tombstones/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tombstone */
        get: operations["read_tombstone_api_v1_audit_tombstones__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Case */
        get: operations["read_case_api_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        /** Delete Case */
        delete: operations["delete_case_api_v1_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Case */
        post: operations["approve_case_api_v1_cases__case_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/facts/{fact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review Fact */
        patch: operations["review_fact_api_v1_cases__case_id__facts__fact_id__patch"];
        trace?: never;
    };
    "/api/v1/cases/{case_id}/memory-image/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Memory Image Content */
        get: operations["read_memory_image_content_api_v1_cases__case_id__memory_image_content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/memory-image/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Memory Image */
        post: operations["decide_memory_image_api_v1_cases__case_id__memory_image_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/memory-image/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Memory Image */
        post: operations["regenerate_memory_image_api_v1_cases__case_id__memory_image_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/rendered-video/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Rendered Video */
        post: operations["retry_rendered_video_api_v1_cases__case_id__rendered_video_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/rendered-video/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Rendered Video */
        get: operations["stream_rendered_video_api_v1_cases__case_id__rendered_video_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cases/{case_id}/routes/{route_id}/steps/{step_index}/narration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Narrate Route Step */
        get: operations["narrate_route_step_api_v1_cases__case_id__routes__route_id__steps__step_index__narration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_v1_sources_get"];
        put?: never;
        /** Create Source */
        post: operations["create_source_api_v1_sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        /** Retire Source */
        delete: operations["retire_source_api_v1_sources__source_id__delete"];
        options?: never;
        head?: never;
        /** Update Source */
        patch: operations["update_source_api_v1_sources__source_id__patch"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        /** Disable User */
        delete: operations["disable_user_api_v1_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Video */
        post: operations["upload_video_api_v1_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Demo Video */
        post: operations["create_demo_video_api_v1_videos_demo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Video From Link
         * @description Baja el video del enlace y lo mete por el mismo camino que un archivo.
         *
         *     Los errores de descarga se traducen a 422 con el motivo tal cual: quien pega
         *     un enlace privado, uno que no es de YouTube o uno que dura una hora tiene
         *     que poder leer cuál de las tres cosas pasó.
         */
        post: operations["create_video_from_link_api_v1_videos_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Analysis */
        post: operations["start_analysis_api_v1_videos__video_id__analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/videos/{video_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Video */
        get: operations["stream_video_api_v1_videos__video_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRead */
        AnalysisRead: {
            current_stage: components["schemas"]["AnalysisStage"] | null;
            /** Events Url */
            events_url: string;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Video Id */
            video_id: string;
        };
        /** AnalysisReadinessRead */
        AnalysisReadinessRead: {
            /** Accepted Media Types */
            accepted_media_types: ("video/mp4" | "video/webm")[];
            /** Anthropic Configured */
            anthropic_configured: boolean;
            /** Beto Available */
            beto_available: boolean;
            /** Can Upload */
            can_upload: boolean;
            /** Ffmpeg Available */
            ffmpeg_available: boolean;
            /** Ffprobe Available */
            ffprobe_available: boolean;
            /**
             * Link Ingest Enabled
             * @default false
             */
            link_ingest_enabled: boolean;
            /**
             * Link Ingest Max Seconds
             * @default 1800
             */
            link_ingest_max_seconds: number;
            /** Max Video Bytes */
            max_video_bytes: number;
            /** Openai Configured */
            openai_configured: boolean;
            /** Video Retention Days */
            video_retention_days: number;
        };
        /**
         * AnalysisStage
         * @enum {string}
         */
        AnalysisStage: "audio" | "transcription" | "people_places" | "dates_facts" | "classification" | "sources" | "timeline" | "routes";
        /** Body_login_api_v1_auth_token_post */
        Body_login_api_v1_auth_token_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** Body_upload_video_api_v1_videos_post */
        Body_upload_video_api_v1_videos_post: {
            /** File */
            file: string;
        };
        /** CaseApprovalRead */
        CaseApprovalRead: {
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /** Id */
            id: string;
            /** Recommendation Status */
            recommendation_status: string;
            /** Status */
            status: string;
            /**
             * Video Delete After
             * Format: date-time
             */
            video_delete_after: string;
            /** Video Retention Days */
            video_retention_days: number;
        };
        /** CaseApprovalRequest */
        CaseApprovalRequest: {
            /** Confirmed Route Types */
            confirmed_route_types: components["schemas"]["RouteType"][];
        };
        /** CaseRead */
        CaseRead: {
            /** Analysis Id */
            analysis_id: string;
            /** Approved At */
            approved_at: string | null;
            /** Classification */
            classification: {
                [key: string]: unknown;
            };
            /** Critical Inconsistencies */
            critical_inconsistencies: number;
            /** Facts */
            facts: components["schemas"]["FactRead"][];
            /** Id */
            id: string;
            memory_image?: components["schemas"]["MemoryImageRead"] | null;
            /** Recommendation Status */
            recommendation_status: string;
            /** Routes */
            routes: components["schemas"]["RouteRead"][];
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
            /** Sources */
            sources: components["schemas"]["SourceRead"][];
            /** Status */
            status: string;
            /** Timeline */
            timeline: components["schemas"]["TimelineEventRead"][];
            /** Video Id */
            video_id: string;
            /** Video Stream Url */
            video_stream_url: string;
        };
        /**
         * ConfidenceBand
         * @enum {string}
         */
        ConfidenceBand: "high" | "medium" | "low";
        /** EvidenceRef */
        EvidenceRef: {
            /** End Ms */
            end_ms: number;
            /** Segment Id */
            segment_id: string;
            /** Start Ms */
            start_ms: number;
        };
        /** FactRead */
        FactRead: {
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Display Value */
            display_value?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["EvidenceRef"][];
            /** Id */
            id: string;
            /** Is Critical */
            is_critical: boolean;
            /** Label */
            label: string;
            origin: components["schemas"]["Origin"];
            /** Provider Values */
            provider_values?: {
                [key: string]: string | number | boolean | string[] | null;
            };
            /** Value */
            value: string | number | boolean | string[] | null;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** FactReviewRequest */
        FactReviewRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "confirm" | "correct";
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Value */
            value?: string | number | boolean | string[] | null;
        };
        /** GroundedClaim */
        GroundedClaim: {
            /** Source Entry Id */
            source_entry_id: string;
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MemoryImageDecisionRead */
        MemoryImageDecisionRead: {
            memory_image: components["schemas"]["MemoryImageRead"];
        };
        /** MemoryImageDecisionRequest */
        MemoryImageDecisionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "approve" | "reject";
        };
        /** MemoryImageRead */
        MemoryImageRead: {
            /** Failure Code */
            failure_code: string | null;
            /** Generation */
            generation: number;
            /** Id */
            id: string;
            /** Image Url */
            image_url: string | null;
            /** Render Status */
            render_status: ("rendering" | "ready" | "failed" | "expired") | null;
            /** Rendered Video Url */
            rendered_video_url: string | null;
            /** Reviewed At */
            reviewed_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "generating" | "pending_review" | "approved" | "rejected" | "failed";
        };
        /**
         * Origin
         * @enum {string}
         */
        Origin: "mentioned" | "inferred" | "contrasted";
        /** ProviderRouteStep */
        ProviderRouteStep: {
            /** Claims */
            claims: components["schemas"]["GroundedClaim"][];
            /** Instructions */
            instructions: string;
            /** Key Point */
            key_point: string;
            /** Title */
            title: string;
        };
        /**
         * RouteApplicability
         * @description Si esta ruta le sirve a esta persona.
         *
         *     El prompt obligaba a construir las tres siempre, así que el modelo emitía
         *     rutas que no creía pertinentes y se cubría con condicionales dentro del
         *     texto: "Esta ruta aplica sólo si usted desea volver…". Decirlo en un campo
         *     es más honesto que esconderlo en la redacción, y deja que quien lee sepa de
         *     entrada cuál de las tres es la suya.
         * @enum {string}
         */
        RouteApplicability: "applies" | "conditional" | "not_applicable";
        /** RouteRead */
        RouteRead: {
            /** @default applies */
            applicability: components["schemas"]["RouteApplicability"];
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Id */
            id: string;
            /** @default inferred */
            origin: components["schemas"]["Origin"];
            /** Provider Options */
            provider_options?: {
                [key: string]: unknown;
            } | null;
            route_type: components["schemas"]["RouteType"];
            /** Steps */
            steps: components["schemas"]["ProviderRouteStep"][];
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /**
         * RouteType
         * @enum {string}
         */
        RouteType: "emergency" | "housing_stabilization" | "return_relocation";
        /** SourceCreate */
        SourceCreate: {
            /** Contact */
            contact: string;
            /** Coverage */
            coverage: string;
            /** Entity */
            entity: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            /** Program */
            program: string;
            /** Requirements */
            requirements: string;
            /** Route Types */
            route_types: components["schemas"]["RouteType"][];
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "contact" | "program";
            /**
             * Status
             * @default active
             */
            status: string;
            /** Url */
            url: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** SourceList */
        SourceList: {
            /** Items */
            items: components["schemas"]["SourceRead"][];
        };
        /** SourceRead */
        SourceRead: {
            /** Contact */
            contact: string;
            /** Coverage */
            coverage: string;
            /** Disclaimer */
            disclaimer: string | null;
            /** Entity */
            entity: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Id */
            id: string;
            /** Is Expired */
            is_expired: boolean;
            /** Program */
            program: string;
            /** Requirements */
            requirements: string;
            /** Route Types */
            route_types: components["schemas"]["RouteType"][];
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "contact" | "program";
            /** Status */
            status: string;
            /** Url */
            url: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
        };
        /** SourceUpdate */
        SourceUpdate: {
            /** Contact */
            contact?: string | null;
            /** Coverage */
            coverage?: string | null;
            /** Entity */
            entity?: string | null;
            /** Expires At */
            expires_at?: string | null;
            /** Program */
            program?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Route Types */
            route_types?: components["schemas"]["RouteType"][] | null;
            /** Source Kind */
            source_kind?: ("contact" | "program") | null;
            /** Status */
            status?: string | null;
            /** Url */
            url?: string | null;
            /** Verified At */
            verified_at?: string | null;
        };
        /** TimelineEventRead */
        TimelineEventRead: {
            confidence_band: components["schemas"]["ConfidenceBand"];
            /** Description */
            description: string;
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            origin: components["schemas"]["Origin"];
            /** Provider Options */
            provider_options?: {
                [key: string]: unknown;
            } | null;
            /** Start Ms */
            start_ms: number;
            /** Title */
            title: string;
            verification_status: components["schemas"]["VerificationStatus"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserRead"];
        };
        /** TombstoneRead */
        TombstoneRead: {
            /** Action */
            action: string;
            /** Actor Role */
            actor_role: string;
            /** Case Id Hash */
            case_id_hash: string;
            /**
             * Deleted At
             * Format: date-time
             */
            deleted_at: string;
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Analysis Id */
            analysis_id?: string | null;
            /** End Ms */
            end_ms: number;
            /** Id */
            id: string;
            /** Order Index */
            order_index?: number | null;
            /** Start Ms */
            start_ms: number;
            /** Text */
            text: string;
            /** Video Id */
            video_id?: string | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserList */
        UserList: {
            /** Items */
            items: components["schemas"]["UserRead"][];
        };
        /** UserRead */
        UserRead: {
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["UserRole"];
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "operador" | "validador" | "admin";
        /** UserUpdate */
        UserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Password */
            password?: string | null;
            role?: components["schemas"]["UserRole"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationStatus
         * @enum {string}
         */
        VerificationStatus: "confirmed" | "pending" | "not_identified" | "inconsistent";
        /**
         * VideoLinkCreate
         * @description El enlace tal como lo pegó quien analiza; se normaliza en el servicio.
         */
        VideoLinkCreate: {
            /** Url */
            url: string;
        };
        /** VideoRead */
        VideoRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Is Demo */
            is_demo: boolean;
            /** Media Type */
            media_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_readiness_api_v1_analyses_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisReadinessRead"];
                };
            };
        };
    };
    stream_analysis_events_api_v1_analyses__analysis_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tombstone_api_v1_audit_tombstones__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TombstoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                senda_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                senda_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_case_api_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_api_v1_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_case_api_v1_cases__case_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseApprovalRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_fact_api_v1_cases__case_id__facts__fact_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                fact_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_memory_image_content_api_v1_cases__case_id__memory_image_content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_memory_image_api_v1_cases__case_id__memory_image_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryImageDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryImageDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_memory_image_api_v1_cases__case_id__memory_image_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryImageDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_rendered_video_api_v1_cases__case_id__rendered_video_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryImageDecisionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_rendered_video_api_v1_cases__case_id__rendered_video_stream_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narrate_route_step_api_v1_cases__case_id__routes__route_id__steps__step_index__narration_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                route_id: string;
                step_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceList"];
                };
            };
        };
    };
    create_source_api_v1_sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_source_api_v1_sources__source_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_source_api_v1_sources__source_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_user_api_v1_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_video_api_v1_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_api_v1_videos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_demo_video_api_v1_videos_demo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
        };
    };
    create_video_from_link_api_v1_videos_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_analysis_api_v1_videos__video_id__analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_video_api_v1_videos__video_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
